# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install python3-sphinx latexmk texlive-latex-extra
        pip install sphinx-rtd-theme
    - name: build doc
      run: |
        # stop the build if there are Python syntax errors or undefined names
        cd postgis-intro/sources/en/
        make html
        make latex
        cd  ../../doc/en/.build/latex
        make all-pdf
        cd ../../../../../
    - name: Upload pdf
      uses: actions/upload-artifact@v2
      with:
        path: postgis-intro/doc/en/.build/latex/*.pdf
        if-no-files-found: warn       